export default [
    " ",
    "#############################################################################################",
    "#                                                                                           #",
    "#<color=\"yellow\">           ______ _            _               _______                                     </color>#",
    "#<color=\"yellow\">          |  ____| |          (_)             |__   __|                                    </color>#",
    "#<color=\"yellow\">          | |__  | | ___  _ __ _  __ _ _ __      | |_ __ __ _ _   _  ___  _ __             </color>#",
    "#<color=\"yellow\">          |  __| | |/ _ \\| '__| |/ _` | '_ \\     | | '__/ _` | | | |/ _ \\| '_ \\            </color>#",
    "#<color=\"yellow\">          | |    | | (_) | |  | | (_| | | | |    | | | | (_| | |_| | (_) | | | |           </color>#",
    "#<color=\"yellow\">          |_|    |_|____/|_|  |_|__,__|_| |_|    |_|_|  \\__,_|\\__, |\\___/|_| |_|           </color>#",
    "#<color=\"yellow\">                                                               __/ |                       </color>#",
    "#<color=\"yellow\">                                                              |___/                        </color>#",
    "#                                                                                           #",
    "#                                 -------------------------                                 #",
    "#                                                                                           #",
    "#    Welcome to Raven Orange 2024.06.1 LTS (GNU/Linux 5.15.0-72-generic x86_64)             #",
    "#    An Open Source Operating System made with love by Raven Industries © 2024              #",
    "#                                                                                           #",
    "#     * Documentation:  <link=\"https://docs.raven.com/systems/orange-2024.06.1-lts\">https://docs.raven.com/systems/orange-2024.06.1-lts</link>                 #",
    "#     * Management:     <link=\"https://admin.raven.com/?id=1e0f7d42-8b39-4c7b-9d2a-03b14f3e7e5b\">https://admin.raven.com/?id=1e0f7d42-8b39-4c7b-9d2a-03b14f3e7e5b</link>    #",
    "#     * Support:        <link=\"https://support.raven.com/?product=raven-orange-2024.06.1-lts\">https://support.raven.com/?product=raven-orange-2024.06.1-lts</link>       #",
    "#                                                                                           #",
    "#    Type 'menu' to see the list of available commands.                                     #",
    "#                                                                                           #",
    "#############################################################################################",
    " "
];
