export default [
    " ",
    "|   <color=\"gray\">// 📚 My personal portfolio website to highlight my skills and projects.</color>",
    "|   <color=\"yellow\">Portfolio</color>                                    <link=\"https://github.com/FlorianLeChat/Portfolio\">https://github.com/FlorianLeChat/Portfolio</link>",
    " ",
    "|   <color=\"gray\">// 🌌 A framework to help developers creating Lua scripts for a sandbox-style video game called Garry's Mod.</color>",
    "|   <color=\"yellow\">Raven Framework</color>",
    " ",
    "|   <color=\"gray\">// 📖 A simple text-based RPG made in Python.</color>",
    "|   <color=\"yellow\">Python RPG</color>                                   <link=\"https://github.com/FlorianLeChat/Python-RPG\">https://github.com/FlorianLeChat/Python-RPG</link>",
    " ",
    "|   <color=\"gray\">// 📥 A simple web page to download addons through the GmodStore API.</color>",
    "|   <color=\"yellow\">GmodStore Downloader</color>                         <link=\"https://github.com/FlorianLeChat/GmodStore-Downloader\">https://github.com/FlorianLeChat/GmodStore-Downloader</link>",
    " ",
    "|   <color=\"gray\">// 📺 A simple web page to download videos through YouTube-DL.</color>",
    "|   <color=\"yellow\">YouTube Downloader</color>                           <link=\"https://github.com/FlorianLeChat/YouTube-Downloader\">https://github.com/FlorianLeChat/YouTube-Downloader</link>",
    " ",
    "|   <color=\"gray\">// 📐 Calculates the size of a Workshop collection through the Steam API.</color>",
    "|   <color=\"yellow\">Steam Collection Download Size Calculator</color>    <link=\"https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator\">https://github.com/FlorianLeChat/Steam-Collection-Download-Size-Calculator</link>",
    " ",
    "|   <color=\"gray\">// 📊 Monitor Git commits for some Facepunch games (e.g. Rust, Garry's Mod, S&Box).</color>",
    "|   <color=\"yellow\">Facepunch Commits Monitor</color>                    <link=\"https://github.com/FlorianLeChat/Facepunch-Commits-Monitor\">https://github.com/FlorianLeChat/Facepunch-Commits-Monitor</link>",
    " ",
    "|   <color=\"gray\">// 💾 A simple, privacy-friendly, secure and high-performance file storage system.</color>",
    "|   <color=\"yellow\">Simple File Storage</color>                          <link=\"https://github.com/FlorianLeChat/Simple-File-Storage\">https://github.com/FlorianLeChat/Simple-File-Storage</link>",
    " ",
    "|   <color=\"gray\">// 🕹️ A proof-of-concept project made during my studies to manage game dedicated servers using the Source RCON protocol through a web interface.</color>",
    "|   <color=\"yellow\">Source Web Console</color>                           <link=\"https://github.com/FlorianLeChat/Source-Web-Console\">https://github.com/FlorianLeChat/Source-Web-Console</link>",
    " ",
    "|   <color=\"gray\">// 📥 A simple web page to download addons through the GmodStore API.</color>",
    "|   <color=\"yellow\">GmodStore Downloader</color>                         <link=\"https://github.com/FlorianLeChat/GmodStore-Downloader\">https://github.com/FlorianLeChat/GmodStore-Downloader</link>",
    " ",
    "|   <color=\"gray\">// 📺 A simple web page to download videos through YouTube-DL.</color>",
    "|   <color=\"yellow\">YouTube Downloader</color>                           <link=\"https://github.com/FlorianLeChat/YouTube-Downloader\">https://github.com/FlorianLeChat/YouTube-Downloader</link>",
    " ",
    "|   <color=\"gray\">// 🏗️ Domego is a serious educational game in which each player takes the role of an actor in a construction operation.</color>",
    "|   <color=\"yellow\">Domego</color>                                       <link=\"https://github.com/FlorianLeChat/Domego\">https://github.com/FlorianLeChat/Domego</link>",
    " ",
    "|   <color=\"gray\">// 👾 A GTA-Like racing game to participate to the \"Games on Web\" (2023) competition.</color>",
    "|   <color=\"yellow\">Have A Break, Save The Planet</color>                <link=\"https://github.com/FlorianLeChat/Games-On-Web-2023\">https://github.com/FlorianLeChat/Games-On-Web-2023</link>",
    " ",
    "|   <color=\"gray\">// 🏠 A terminal-style home page to browse my personal projects (hey, is this the current website?!).</color>",
    "|   <color=\"yellow\">Homepage</color>                                     <link=\"https://github.com/FlorianLeChat/Homepage\">https://github.com/FlorianLeChat/Homepage</link>",
    " ",
    "|   <color=\"gray\">// 🔗 An URL Shortener designed to be easy to use, inherently secure and fully customizable, with a strong emphasis on privacy and a fully independent API.</color>",
    "|   <color=\"yellow\">Raven Url Shortener</color>                          <link=\"https://github.com/FlorianLeChat/Raven-Url-Shortener\">https://github.com/FlorianLeChat/Raven-Url-Shortener</link>",
    " ",
    "|   <color=\"gray\">// 👨‍💼 An online resume designed to be dynamic, customizable and perfectly adaptable to all media.</color>",
    "|   <color=\"yellow\">Online Resume</color>                                <link=\"https://github.com/FlorianLeChat/Online-Resume\">https://github.com/FlorianLeChat/Online-Resume</link>",
    " ",
    "|   <color=\"gray\">// ⏳ A countdown website for future or past dates, ensuring you never forget how time flies.</color>",
    "|   <color=\"yellow\">TimeLoop</color>                                     <link=\"https://github.com/FlorianLeChat/TimeLoop\">https://github.com/FlorianLeChat/TimeLoop</link>",
    " ",
    "|   <color=\"gray\">// ✒️ A blog from a simple man who wants to share his own thoughts.</color>",
    "|   <color=\"yellow\">Blog</color>                                         <link=\"https://blog.florian-dev.fr/\">https://blog.florian-dev.fr/</link>",
    " ",
    "|   <color=\"gray\">// 🔮 A website designed to answer every question you can imagine.</color>",
    "|   <color=\"yellow\">Magic Answers</color>                                <link=\"https://github.com/FlorianLeChat/Magic-Answers\">https://github.com/FlorianLeChat/Magic-Answers</link>",
    " "
];
